input {
  gelf {
    port => 5044
  }
}

filter {
  # Contoh: bisa tambahin parsing JSON atau custom field
  if [level] {
    mutate { add_field => { "log_level" => "%{level}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
