input {
  gelf {
    port => 5044
    codec => "json"
  }
}

filter {
  # Optional, bisa ditambahkan jika ingin parse log JSON
  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "rest-service-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
